#!/bin/bash

if [[ $# -lt 1 ]]
then
	echo "Usage: ./count [username] (-c optional)"
	exit 1
fi

user=$1

if ! [[ -d $user ]]
then
	echo "ERROR: $user/ does not exist."
	exit 1
fi


dirs=$(find $user/ -maxdepth 1 -type d)

for dir in $dirs
do
	if [[ "$dir" != "$user/" ]]
	then
		buffer="${buffer}$dir\n"
	fi
done

if [[ $2 == "-c" ]]
then
	echo "$(echo -e -n "$buffer" | wc -l)"
else
	echo "There are $(echo -e -n "$buffer" | wc -l) active repositories here."
fi
