#!/bin/bash

if [[ $# -lt 1 ]]
then
	echo "Usage: ./pull [username]"
	exit 1
fi

user=$1

if ! [[ -d $user ]]
then
	echo "ERROR: $user/ does not exist."
	exit 1
fi


cd $user
dirs=$(find . -maxdepth 1 -type d)

for dir in $dirs
do
	if [[ "$dir" != "." ]]
	then
		cd $dir
		if git pull --all > /dev/null 2>&1
		then
			echo "$(echo "$dir" | cut -c3-) has been updated."
			cd ..
		else
			echo "$(echo "$dir" | cut -c3-) is not on github anymore. Moving to Outdated/"
			cd ../../
			if ! [[ -d Outdated ]]
			then
				mkdir Outdated
			fi	
			mv $user/$dir Outdated/
			cd $user
		fi
	fi
done
